### ISSUE TITLE
Is youtube-dl-flatpak updated as often as youtube-dl ?

### ISSUE THREAD

**Issue by antistress** [nedrichards/youtube-dl-flatpak#2]
Hi,
I'm interested in having a base Debian GNOME system in .deb and my softwares in flatpak
Sadly flathub seems to only propose GUI applications and I miss youtube-dl
Therefore I'm glad to find this project, thanks for it :)

One thing : is youtube-dl-flatpak updated as often as youtube-dl ?
your master branch says " Updated 2 years ago by wjt"

Thanks

**Comment by nedrichards** [comment]
it's a good thing to have an immutable base system and then layer functionality on top of that. I tend to use toolbox https://github.com/containers/toolbox or podman to get CLI apps working in that kind of system myself https://github.com/containers/libpod that way you get to reuse things like the docker ecosystem more easily.

This repo is entirely out of date - and in fact I'll archive it shortly, but if you must use a flatpak then you could install an app from flathub that contains youtube-dl (this search gives a good look https://github.com/search?q=org%3Aflathub+youtube-dl&type=Code ) and then do something like `flatpak run --command=bash --filesystem=home  com.github.JannikHv.Gydl` that will drop you into a shell inside the flatpak container and you can access the copy of youtube-dl bundled inside there from inside /app. And if you want those apps to keep up to date then feel free to send pull requests!
